first_project/first_app/urls.py
from django.urls import path
from first_app import views
from django.conf.urls import include

app_name = 'first_app'

urlpatterns = [
    path('help/',views.help,name='help'),
    path('register/',views.register,name='register'),
    # path('users/',views.user_display,name='users'),
    
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views
from django.conf.urls import include

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('first_app/', include('first_app.urls')),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_url = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pic',blank=True)

    def __str__(self):
        return self.user.username
    

first_project/first_app/forms.py
from django import forms
from first_app.models import UserProfileInfo
from django.contrib.auth.models import User

class UserInfo(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):

    class Meta:

        model = UserProfileInfo

        fields = ('portfolio_url','profile_pic')        
    

first_project/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import *
from first_app.forms import UserInfo,UserProfileInfoForm
# Create your views here.


def index(request):
    my_dict = {'text':'Hello Im from views.py','number':100}
    
    return render(request,'index.html',context=my_dict)

def help(request):
    my_help = {'help':'If you need any Help feel free to Contact us!'}
    return render(request,'help.html',context=my_help)

def register(request):
    registerd = False
    if request.method == "POST":
        user_form = UserInfo(data=request.POST) 
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()  

            registerd = True 
        else:
            print(user_form.errors,profile_form.errors)     
    else:
        user_form = UserInfo()
        profile_form = UserProfileInfoForm()
    return render(request,'register.html',
                  {
                    'user_form':user_form,
                    'profile_form':profile_form,
                    'registerd':registerd
                  })

# def user_display(request):
#     user_list = User.objects.all()

#     return render(request,'user.html',{'users':user_list})

first_project/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <title>Title</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>

<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
          <div class="container">
            <ul class="nav navbar-nav ">
                <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
                <li><a class="nav-link" href="{% url 'admin:index'%}">ADMIN</a></li>
                <li><a class="nav-link" href="{% url 'first_app:register'%}">FORMS</a></li>
                <li><a class="nav-link" href="{% url 'first_app:help'%}">HELP</a></li>
            </ul>
      </div>
    </nav>
  </header>
  <main>
    <div class="container">

        {% block body_block %}
        <!-- Anythink outside this will inherited if you will extends to other file -->
        {% endblock %}
    </div>
  </main>
  <footer>
    <!-- place footer here -->
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

first_project/templates/help.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block body_block %}
    
    <h1>Hello This is the Help Section</h1>
    <p>{{help}}</p>
    
{% endblock %}

first_project/templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block body_block %}
<!-- {% load static %} -->
    <h1>First Project</h1>
    <h2><em>Hello Im From index.html</em></h2>
    <br>
    <h3>{{ text|cut:'from' }}</h3>
    <h3>{{ number }}</h3>
    <br>
    <a href="{% url 'first_app:register'%}">Click on This to Create new User!</a>
    <br>
   
    <br>
    <!-- <img src="{% static 'images/img.jpg' %}" > -->

 {% endblock %}   

first_project/templates/register.html
<!DOCTYPE html>
{% extends "base.html" %}

{% load static%}
{% block body_block %}
    <div class="jumbotron">
        {% if registerd %}
            <h1>Thank You for Registration</h1>
        {% else %}
            <h1>Register Here!</h1>
            <h3>Fill out the Following Form!</h3>
            <form enctype="multipart/form-data" method="post"> {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}

first_project/templates/user.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block body_block %}
    <div class="container">
        <h1>Here are the Details of All Users!</h1>
        {% if users%}
            <ol>
                {% for person in users%}
                    <li>User Info</li>
                    <ul>
                        <li>{{ person.first_name}}</li>
                        <li>{{ person.last_name}}</li>
                        <li>{{ person.email}}</li>
                    </ul>
                {% endfor %}    
            </ol>
        {% endif %}    
    </div>
{% endblock %}